/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * If the objective has a known UI label, this enumeration will represent it.
 */
export type DestinyDestinyObjectiveUiStyle = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const DestinyDestinyObjectiveUiStyle = {
    NUMBER_0: 0 as DestinyDestinyObjectiveUiStyle,
    NUMBER_1: 1 as DestinyDestinyObjectiveUiStyle,
    NUMBER_2: 2 as DestinyDestinyObjectiveUiStyle,
    NUMBER_3: 3 as DestinyDestinyObjectiveUiStyle,
    NUMBER_4: 4 as DestinyDestinyObjectiveUiStyle,
    NUMBER_5: 5 as DestinyDestinyObjectiveUiStyle,
    NUMBER_6: 6 as DestinyDestinyObjectiveUiStyle
};

