/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyCharacterDestinyCharacterCustomization } from './destinyCharacterDestinyCharacterCustomization';


/**
 * This is actually something that Spasm.js *doesn\'t* do right now, and that we don\'t return assets for yet. This is the data about what character customization options you picked. You can combine this with DestinyCharacterCustomizationOptionDefinition to show some cool info, and hopefully someday to actually render a user\'s face in 3D. We\'ll see if we ever end up with time for that.
 */
export interface DestinyEntitiesCharactersDestinyCharacterRenderComponentCustomization { 
    personality?: number;
    face?: number;
    skinColor?: number;
    lipColor?: number;
    eyeColor?: number;
    hairColors?: Array<number>;
    featureColors?: Array<number>;
    decalColor?: number;
    wearHelmet?: boolean;
    hairIndex?: number;
    featureIndex?: number;
    decalIndex?: number;
}

