/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DictionaryComponentResponseOfuint32AndDestinyVendorCategoriesComponent } from './dictionaryComponentResponseOfuint32AndDestinyVendorCategoriesComponent';
import { DestinyEntitiesVendorsDestinyVendorCategoriesComponent } from './destinyEntitiesVendorsDestinyVendorCategoriesComponent';


/**
 * Categories that the vendor has available, and references to the sales therein. These are keyed by the Vendor Hash, so you will get one Categories Component per vendor returned.  COMPONENT TYPE: VendorCategories
 */
export interface DestinyResponsesDestinyVendorsResponseCategories { 
    data?: { [key: string]: DestinyEntitiesVendorsDestinyVendorCategoriesComponent; };
    privacy?: number;
    /**
     * If true, this component is disabled.
     */
    disabled?: boolean;
}

