/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsItemsDestinyEnergyCapacityEntry } from './destinyDefinitionsItemsDestinyEnergyCapacityEntry';


/**
 * IF not null, this plug provides Energy capacity to the item in which it is socketed. In Armor 2.0 for example, is implemented in a similar way to Masterworks, where visually it\'s a single area of the UI being clicked on to \"Upgrade\" to higher energy levels, but it\'s actually socketing new plugs.
 */
export interface DestinyDefinitionsItemsDestinyItemPlugDefinitionEnergyCapacity { 
    /**
     * How much energy capacity this plug provides.
     */
    capacityValue?: number;
    /**
     * Energy provided by a plug is always of a specific type - this is the hash identifier for the energy type for which it provides Capacity.
     */
    energyTypeHash?: number;
    /**
     * The Energy Type for this energy capacity, in enum form for easy use.
     */
    energyType?: number;
}

