/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyComponentsInventoryDestinyCurrenciesComponent } from './destinyComponentsInventoryDestinyCurrenciesComponent';
import { SingleComponentResponseOfDestinyCurrenciesComponent } from './singleComponentResponseOfDestinyCurrenciesComponent';


/**
 * A \"lookup\" convenience component that can be used to quickly check if the character has access to items that can be used for purchasing.  COMPONENT TYPE: CurrencyLookups
 */
export interface DestinyResponsesDestinyCharacterResponseCurrencyLookups { 
    data?: DestinyComponentsInventoryDestinyCurrenciesComponent;
    privacy?: number;
    /**
     * If true, this component is disabled.
     */
    disabled?: boolean;
}

