/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsDestinyNodeActivationRequirement } from "./destinyDefinitionsDestinyNodeActivationRequirement";

/**
 * If the step has requirements for activation (they almost always do, if nothing else than for the Talent Grid\'s Progression to have reached a certain level), they will be defined here.
 */
export interface DestinyDefinitionsDestinyNodeStepDefinitionActivationRequirement {
  /**
   * The Progression level on the Talent Grid required to activate this node.  See DestinyTalentGridDefinition.progressionHash for the related Progression, and read DestinyProgressionDefinition\'s documentation to learn more about Progressions.
   */
  gridLevel?: number;
  /**
   * The list of hash identifiers for material requirement sets: materials that are required for the node to be activated. See DestinyMaterialRequirementSetDefinition for more information about material requirements.  In this case, only a single DestinyMaterialRequirementSetDefinition will be chosen from this list, and we won\'t know which one will be chosen until an instance of the item is created.
   */
  materialRequirementHashes?: Array<number>;
}
