/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyHistoricalStatsDestinyHistoricalStatsValuePair } from "./destinyHistoricalStatsDestinyHistoricalStatsValuePair";

/**
 * Weighted value of the stat if a weight greater than 1 has been assigned.
 */
export interface DestinyHistoricalStatsDestinyHistoricalStatsValueWeighted {
  /**
   * Raw value of the statistic
   */
  value?: number;
  /**
   * Localized formated version of the value.
   */
  displayValue?: string;
}
