/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsItemsDestinyEnergyCostEntry } from './destinyDefinitionsItemsDestinyEnergyCostEntry';


/**
 * IF not null, this plug has an energy cost. This contains the details of that cost.
 */
export interface DestinyDefinitionsItemsDestinyItemPlugDefinitionEnergyCost { 
    /**
     * The Energy cost for inserting this plug.
     */
    energyCost?: number;
    /**
     * The type of energy that this plug costs, as a reference to the DestinyEnergyTypeDefinition of the energy type.
     */
    energyTypeHash?: number;
    /**
     * The type of energy that this plug costs, in enum form.
     */
    energyType?: number;
}

