/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsDestinyItemStatBlockDefinition } from './destinyDefinitionsDestinyItemStatBlockDefinition';
import { DestinyDefinitionsDestinyInventoryItemStatDefinition } from './destinyDefinitionsDestinyInventoryItemStatDefinition';


/**
 * If this item can have stats (such as a weapon, armor, or vehicle), this block will be non-null and populated with the stats found on the item.
 */
export interface DestinyDefinitionsDestinyInventoryItemDefinitionStats { 
    /**
     * If true, the game won\'t show the \"primary\" stat on this item when you inspect it.  NOTE: This is being manually mapped, because I happen to want it in a block that isn\'t going to directly create this derivative block.
     */
    disablePrimaryStatDisplay?: boolean;
    /**
     * If the item\'s stats are meant to be modified by a DestinyStatGroupDefinition, this will be the identifier for that definition.  If you are using live data or precomputed stats data on the DestinyInventoryItemDefinition.stats.stats property, you don\'t have to worry about statGroupHash and how it alters stats: the already altered stats are provided to you. But if you want to see how the sausage gets made, or perform computations yourself, this is valuable information.
     */
    statGroupHash?: number;
    /**
     * If you are looking for precomputed values for the stats on a weapon, this is where they are stored. Technically these are the \"Display\" stat values. Please see DestinyStatsDefinition for what Display Stat Values means, it\'s a very long story... but essentially these are the closest values BNet can get to the item stats that you see in-game.  These stats are keyed by the DestinyStatDefinition\'s hash identifier for the stat that\'s found on the item.
     */
    stats?: { [key: string]: DestinyDefinitionsDestinyInventoryItemStatDefinition; };
    /**
     * A quick and lazy way to determine whether any stat other than the \"primary\" stat is actually visible on the item. Items often have stats that we return in case people find them useful, but they\'re not part of the \"Stat Group\" and thus we wouldn\'t display them in our UI. If this is False, then we\'re not going to display any of these stats other than the primary one.
     */
    hasDisplayableStats?: boolean;
    /**
     * This stat is determined to be the \"primary\" stat, and can be looked up in the stats or any other stat collection related to the item.  Use this hash to look up the stat\'s value using DestinyInventoryItemDefinition.stats.stats, and the renderable data for the primary stat in the related DestinyStatDefinition.
     */
    primaryBaseStatHash?: number;
}

