/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsDestinyItemGearsetBlockDefinition } from "./destinyDefinitionsDestinyItemGearsetBlockDefinition";

/**
 * If this item has related items in a \"Gear Set\", this will be non-null and the relationships defined herein.
 */
export interface DestinyDefinitionsDestinyInventoryItemDefinitionGearset {
  /**
   * The maximum possible number of items that can be collected.
   */
  trackingValueMax?: number;
  /**
   * The list of hashes for items in the gearset. Use them to look up DestinyInventoryItemDefinition entries for the items in the set.
   */
  itemList?: Array<number>;
}
