/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsDestinyItemValueBlockDefinition } from "./destinyDefinitionsDestinyItemValueBlockDefinition";
import { DestinyDestinyItemQuantity } from "./destinyDestinyItemQuantity";

/**
 * The conceptual \"Value\" of an item, if any was defined. See the DestinyItemValueBlockDefinition for more details.
 */
export interface DestinyDefinitionsDestinyInventoryItemDefinitionValue {
  /**
   * References to the items that make up this item\'s \"value\", and the quantity.
   */
  itemValue?: Array<DestinyDestinyItemQuantity>;
  /**
   * If there\'s a localized text description of the value provided, this will be said description.
   */
  valueDescription?: string;
}
