/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyHistoricalStatsDestinyPostGameCarnageReportEntry } from './destinyHistoricalStatsDestinyPostGameCarnageReportEntry';
import { DestinyHistoricalStatsDestinyPostGameCarnageReportTeamEntry } from './destinyHistoricalStatsDestinyPostGameCarnageReportTeamEntry';
import { DestinyHistoricalStatsDestinyPostGameCarnageReportDataActivityDetails } from './destinyHistoricalStatsDestinyPostGameCarnageReportDataActivityDetails';


export interface DestinyHistoricalStatsDestinyPostGameCarnageReportData { 
    /**
     * Date and time for the activity.
     */
    period?: string;
    /**
     * If this activity has \"phases\", this is the phase at which the activity was started. This value is only valid for activities before the Beyond Light expansion shipped. Subsequent activities will not have a valid value here.
     */
    startingPhaseIndex?: number;
    /**
     * True if the activity was started from the beginning, if that information is available and the activity was played post Witch Queen release.
     */
    activityWasStartedFromBeginning?: boolean;
    activityDetails?: DestinyHistoricalStatsDestinyPostGameCarnageReportDataActivityDetails;
    /**
     * Collection of players and their data for this activity.
     */
    entries?: Array<DestinyHistoricalStatsDestinyPostGameCarnageReportEntry>;
    /**
     * Collection of stats for the player in this activity.
     */
    teams?: Array<DestinyHistoricalStatsDestinyPostGameCarnageReportTeamEntry>;
}

