/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyComponentsVendorsDestinyVendorGroupComponent } from './destinyComponentsVendorsDestinyVendorGroupComponent';
import { SingleComponentResponseOfDestinyVendorGroupComponent } from './singleComponentResponseOfDestinyVendorGroupComponent';


/**
 * For Vendors being returned, this will give you the information you need to group them and order them in the same way that the Bungie Companion app performs grouping. It will automatically be returned if you request the Vendors component.  COMPONENT TYPE: Vendors
 */
export interface DestinyResponsesDestinyVendorsResponseVendorGroups { 
    data?: DestinyComponentsVendorsDestinyVendorGroupComponent;
    privacy?: number;
    /**
     * If true, this component is disabled.
     */
    disabled?: boolean;
}

