/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DictionaryComponentResponseOfuint32AndDestinyItemObjectivesComponent } from "./dictionaryComponentResponseOfuint32AndDestinyItemObjectivesComponent";
import { DictionaryComponentResponseOfuint32AndDestinyItemPerksComponent } from "./dictionaryComponentResponseOfuint32AndDestinyItemPerksComponent";
import { DestinyBaseItemComponentSetOfuint32 } from "./destinyBaseItemComponentSetOfuint32";

/**
 * The set of components belonging to the player\'s UNinstanced items. Because apparently now those too can have information relevant to the character\'s state.  COMPONENT TYPE: [See inside the DestinyItemComponentSet contract for component types.]
 */
export interface DestinyResponsesDestinyCharacterResponseUninstancedItemComponents {
  objectives?: DictionaryComponentResponseOfuint32AndDestinyItemObjectivesComponent;
  perks?: DictionaryComponentResponseOfuint32AndDestinyItemPerksComponent;
}
