/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyComponentsItemsDestinyItemReusablePlugsComponent } from './destinyComponentsItemsDestinyItemReusablePlugsComponent';
import { SingleComponentResponseOfDestinyItemReusablePlugsComponent } from './singleComponentResponseOfDestinyItemReusablePlugsComponent';


/**
 * Information about the Reusable Plugs for sockets on an item. These are plugs that you can insert into the given socket regardless of if you actually own an instance of that plug: they are logic-driven plugs rather than inventory-driven.   These may need to be combined with Plug Set component data to get a full picture of available plugs on a given socket.   COMPONENT TYPE: ItemReusablePlugs
 */
export interface DestinyResponsesDestinyItemResponseReusablePlugs { 
    data?: DestinyComponentsItemsDestinyItemReusablePlugsComponent;
    privacy?: number;
    /**
     * If true, this component is disabled.
     */
    disabled?: boolean;
}

