/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyChallengesDestinyChallengeStatusObjective } from './destinyChallengesDestinyChallengeStatusObjective';


/**
 * Represents the status and other related information for a challenge that is - or was - available to a player.   A challenge is a bonus objective, generally tacked onto Quests or Activities, that provide additional variations on play.
 */
export interface DestinyChallengesDestinyChallengeStatus { 
    objective?: DestinyChallengesDestinyChallengeStatusObjective;
}

