/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyMilestonesDestinyMilestoneActivityCompletionStatus } from './destinyMilestonesDestinyMilestoneActivityCompletionStatus';
import { DestinyMilestonesDestinyMilestoneActivityPhase } from './destinyMilestonesDestinyMilestoneActivityPhase';


/**
 * An OPTIONAL component: if it makes sense to talk about this activity variant in terms of whether or not it has been completed or what progress you have made in it, this will be returned. Otherwise, this will be NULL.
 */
export interface DestinyMilestonesDestinyMilestoneActivityVariantCompletionStatus { 
    /**
     * If the activity has been \"completed\", that information will be returned here.
     */
    completed?: boolean;
    /**
     * If the Activity has discrete \"phases\" that we can track, that info will be here. Otherwise, this value will be NULL. Note that this is a list and not a dictionary: the order implies the ascending order of phases or progression in this activity.
     */
    phases?: Array<DestinyMilestonesDestinyMilestoneActivityPhase>;
}

