/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsDestinyItemMetricBlockDefinition } from "./destinyDefinitionsDestinyItemMetricBlockDefinition";

/**
 * If this item has available metrics to be shown, this block will be non-null have the appropriate hashes defined.
 */
export interface DestinyDefinitionsDestinyInventoryItemDefinitionMetrics {
  /**
   * Hash identifiers for any DestinyPresentationNodeDefinition entry that can be used to list available metrics. Any metric listed directly below these nodes, or in any of these nodes\' children will be made available for selection.
   */
  availableMetricCategoryNodeHashes?: Array<number>;
}
