/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDestinyStat } from './destinyDestinyStat';


/**
 * The item stat that we consider to be \"primary\" for the item. For instance, this would be \"Attack\" for Weapons or \"Defense\" for armor.
 */
export interface DestinyEntitiesItemsDestinyItemInstanceComponentPrimaryStat { 
    /**
     * The hash identifier for the Stat. Use it to look up the DestinyStatDefinition for static data about the stat.
     */
    statHash?: number;
    /**
     * The current value of the Stat.
     */
    value?: number;
}

