/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyComponentsKiosksDestinyKioskItemFlavorObjective } from "./destinyComponentsKiosksDestinyKioskItemFlavorObjective";

export interface DestinyComponentsKiosksDestinyKioskItem {
  /**
   * The index of the item in the related DestinyVendorDefintion\'s itemList property, representing the sale.
   */
  index?: number;
  /**
   * If true, the user can not only see the item, but they can acquire it. It is possible that a user can see a kiosk item and not be able to acquire it.
   */
  canAcquire?: boolean;
  /**
   * Indexes into failureStrings for the Vendor, indicating the reasons why it failed if any.
   */
  failureIndexes?: Array<number>;
  flavorObjective?: DestinyComponentsKiosksDestinyKioskItemFlavorObjective;
}
