/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DictionaryComponentResponseOfuint32AndPublicDestinyVendorSaleItemSetComponent } from "./dictionaryComponentResponseOfuint32AndPublicDestinyVendorSaleItemSetComponent";
import { DestinyResponsesPublicDestinyVendorSaleItemSetComponent } from "./destinyResponsesPublicDestinyVendorSaleItemSetComponent";

/**
 * Sales, keyed by the vendorItemIndex of the item being sold. These are keyed by the Vendor Hash, so you will get one Sale Item Set Component per vendor returned.  Note that within the Sale Item Set component, the sales are themselves keyed by the vendorSaleIndex, so you can relate it to the corrent sale item definition within the Vendor\'s definition.  COMPONENT TYPE: VendorSales
 */
export interface DestinyResponsesDestinyPublicVendorsResponseSales {
  data?: {
    [key: string]: DestinyResponsesPublicDestinyVendorSaleItemSetComponent;
  };
  privacy?: number;
  /**
   * If true, this component is disabled.
   */
  disabled?: boolean;
}
