/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyResponsesDestinyVendorsResponseSales } from './destinyResponsesDestinyVendorsResponseSales';
import { DestinyResponsesDestinyCharacterResponseCurrencyLookups } from './destinyResponsesDestinyCharacterResponseCurrencyLookups';
import { DestinyResponsesDestinyVendorsResponseVendorGroups } from './destinyResponsesDestinyVendorsResponseVendorGroups';
import { DestinyResponsesDestinyVendorsResponseStringVariables } from './destinyResponsesDestinyVendorsResponseStringVariables';
import { DestinyResponsesDestinyVendorsResponseCategories } from './destinyResponsesDestinyVendorsResponseCategories';
import { DestinyResponsesDestinyVendorsResponseVendors } from './destinyResponsesDestinyVendorsResponseVendors';
import { DestinyItemComponentSetOfint32 } from './destinyItemComponentSetOfint32';


/**
 * A Response containing all of the components for all requested vendors.
 */
export interface DestinyResponsesDestinyVendorsResponse { 
    vendorGroups?: DestinyResponsesDestinyVendorsResponseVendorGroups;
    vendors?: DestinyResponsesDestinyVendorsResponseVendors;
    categories?: DestinyResponsesDestinyVendorsResponseCategories;
    sales?: DestinyResponsesDestinyVendorsResponseSales;
    /**
     * The set of item detail components, one set of item components per Vendor. These are keyed by the Vendor Hash, so you will get one Item Component Set per vendor returned.  The components contained inside are themselves keyed by the vendorSaleIndex, and will have whatever item-level components you requested (Sockets, Stats, Instance data etc...) per item being sold by the vendor.
     */
    itemComponents?: { [key: string]: DestinyItemComponentSetOfint32; };
    currencyLookups?: DestinyResponsesDestinyCharacterResponseCurrencyLookups;
    stringVariables?: DestinyResponsesDestinyVendorsResponseStringVariables;
}

