/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyCharacterDestinyCharacterPeerView } from "./destinyCharacterDestinyCharacterPeerView";
import { DestinyCharacterDestinyItemPeerView } from "./destinyCharacterDestinyItemPeerView";

/**
 * A minimal view of:  - Equipped items  - The rendering-related custom options on those equipped items  Combined, that should be enough to render all of the items on the equipped character.
 */
export interface DestinyEntitiesCharactersDestinyCharacterRenderComponentPeerView {
  equipment?: Array<DestinyCharacterDestinyItemPeerView>;
}
