/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyEntitiesItemsDestinyItemSocketsComponent } from "./destinyEntitiesItemsDestinyItemSocketsComponent";
import { SingleComponentResponseOfDestinyItemSocketsComponent } from "./singleComponentResponseOfDestinyItemSocketsComponent";

/**
 * Information about the sockets of the item: which are currently active, what potential sockets you could have and the stats/abilities/perks you can gain from them.  COMPONENT TYPE: ItemSockets
 */
export interface DestinyResponsesDestinyItemResponseSockets {
  data?: DestinyEntitiesItemsDestinyItemSocketsComponent;
  privacy?: number;
  /**
   * If true, this component is disabled.
   */
  disabled?: boolean;
}
