/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsDestinyItemSourceBlockDefinition } from "./destinyDefinitionsDestinyItemSourceBlockDefinition";
import { DestinyDefinitionsSourcesDestinyItemSourceDefinition } from "./destinyDefinitionsSourcesDestinyItemSourceDefinition";
import { DestinyDefinitionsDestinyItemVendorSourceReference } from "./destinyDefinitionsDestinyItemVendorSourceReference";

/**
 * If this item has a known source, this block will be non-null and populated with source information. Unfortunately, at this time we are not generating sources: that is some aggressively manual work which we didn\'t have time for, and I\'m hoping to get back to at some point in the future.
 */
export interface DestinyDefinitionsDestinyInventoryItemDefinitionSourceData {
  /**
   * The list of hash identifiers for Reward Sources that hint where the item can be found (DestinyRewardSourceDefinition).
   */
  sourceHashes?: Array<number>;
  /**
   * A collection of details about the stats that were computed for the ways we found that the item could be spawned.
   */
  sources?: Array<DestinyDefinitionsSourcesDestinyItemSourceDefinition>;
  /**
   * If we found that this item is exclusive to a specific platform, this will be set to the BungieMembershipType enumeration that matches that platform.
   */
  exclusive?: number;
  /**
   * A denormalized reference back to vendors that potentially sell this item.
   */
  vendorSources?: Array<DestinyDefinitionsDestinyItemVendorSourceReference>;
}
