/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsDestinyItemSackBlockDefinition } from "./destinyDefinitionsDestinyItemSackBlockDefinition";

/**
 * If this item is a \"reward sack\" that can be opened to provide other items, this will be non-null and the properties of the sack contained herein.
 */
export interface DestinyDefinitionsDestinyInventoryItemDefinitionSack {
  /**
   * A description of what will happen when you open the sack. As far as I can tell, this is blank currently. Unknown whether it will eventually be populated with useful info.
   */
  detailAction?: string;
  /**
   * The localized name of the action being performed when you open the sack.
   */
  openAction?: string;
  selectItemCount?: number;
  vendorSackType?: string;
  openOnAcquire?: boolean;
}
