/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyDefinitionsDestinyTalentNodeStepGroups } from "./destinyDefinitionsDestinyTalentNodeStepGroups";

/**
 * An old holdover from the original Armory, this was an attempt to group perks by functionality.  It is as yet unpopulated, and there will be quite a bit of work needed to restore it to its former working order.
 */
export interface DestinyDefinitionsDestinySandboxPerkDefinitionPerkGroups {
  weaponPerformance?: number;
  impactEffects?: number;
  guardianAttributes?: number;
  lightAbilities?: number;
  damageTypes?: number;
}
