/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyComponentsProfilesDestinyProfileProgressionComponent } from "./destinyComponentsProfilesDestinyProfileProgressionComponent";
import { SingleComponentResponseOfDestinyProfileProgressionComponent } from "./singleComponentResponseOfDestinyProfileProgressionComponent";

/**
 * When we have progression information - such as Checklists - that may apply profile-wide, it will be returned here rather than in the per-character progression data.  COMPONENT TYPE: ProfileProgression
 */
export interface DestinyResponsesDestinyProfileResponseProfileProgression {
  data?: DestinyComponentsProfilesDestinyProfileProgressionComponent;
  privacy?: number;
  /**
   * If true, this component is disabled.
   */
  disabled?: boolean;
}
