/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyComponentsCraftablesDestinyCraftableSocketComponent } from './destinyComponentsCraftablesDestinyCraftableSocketComponent';


export interface DestinyComponentsCraftablesDestinyCraftableComponent { 
    visible?: boolean;
    /**
     * If the requirements are not met for crafting this item, these will index into the list of failure strings.
     */
    failedRequirementIndexes?: Array<number>;
    /**
     * Plug item state for the crafting sockets.
     */
    sockets?: Array<DestinyComponentsCraftablesDestinyCraftableSocketComponent>;
}

