/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyHistoricalStatsDestinyHistoricalStatsValue } from './destinyHistoricalStatsDestinyHistoricalStatsValue';
import { DestinyHistoricalStatsDestinyHistoricalStatsValueBasic } from './destinyHistoricalStatsDestinyHistoricalStatsValueBasic';
import { DestinyHistoricalStatsDestinyHistoricalStatsValueWeighted } from './destinyHistoricalStatsDestinyHistoricalStatsValueWeighted';
import { DestinyHistoricalStatsDestinyHistoricalStatsValuePga } from './destinyHistoricalStatsDestinyHistoricalStatsValuePga';


/**
 * Value of the stat for this player
 */
export interface DestinyHistoricalStatsDestinyLeaderboardEntryValue { 
    /**
     * Unique ID for this stat
     */
    statId?: string;
    basic?: DestinyHistoricalStatsDestinyHistoricalStatsValueBasic;
    pga?: DestinyHistoricalStatsDestinyHistoricalStatsValuePga;
    weighted?: DestinyHistoricalStatsDestinyHistoricalStatsValueWeighted;
    /**
     * When a stat represents the best, most, longest, fastest or some other personal best, the actual activity ID where that personal best was established is available on this property.
     */
    activityId?: number;
}

