/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinyMilestonesDestinyMilestoneContentItemCategory } from './destinyMilestonesDestinyMilestoneContentItemCategory';
import { DestinyMilestonesDestinyMilestoneContent } from './destinyMilestonesDestinyMilestoneContent';


/**
 * A destiny event will not necessarily have milestone \"custom content\", but if it does the details will be here.
 */
export interface TrendingTrendingEntryDestinyRitualEventContent { 
    /**
     * The \"About this Milestone\" text from the Firehose.
     */
    about?: string;
    /**
     * The Current Status of the Milestone, as driven by the Firehose.
     */
    status?: string;
    /**
     * A list of tips, provided by the Firehose.
     */
    tips?: Array<string>;
    /**
     * If DPS has defined items related to this Milestone, they can categorize those items in the Firehose. That data will then be returned as item categories here.
     */
    itemCategories?: Array<DestinyMilestonesDestinyMilestoneContentItemCategory>;
}

